---
- name: Add Suricata APT repository
  apt_repository: repo='ppa:oisf/suricata-stable' state=present

- name: Install required packages
  apt: pkg={{ item }} state=latest
  with_items:
          - suricata
          - oinkmaster
          - sysv-rc-conf

- name: Create required directories
  command: 'mkdir -p {{ item }}'
  with_items:
    - "{{ suricata_log_dir }}"
    - "{{ suricata_log_dir }}"
    - "{{ suricata_log_dir_certs }}"
    - "{{ suricata_rules_dir }}"
  tags:
    - create-suricata-dirs


- name: Creating required files
  command: touch /etc/suricata//threshold.config
  tags:
    - create-suricata-files

- name: DISABLE - Network sniffing interface offloading
  command: "{{item}} chdir=/opt"
  with_items:
    - ethtool -K {{suricata_sniffing_interface}} tso off
    - ethtool -K {{suricata_sniffing_interface}} gro off
    - ethtool -K {{suricata_sniffing_interface}} lro off
    - ethtool -K {{suricata_sniffing_interface}} gso off
    - ethtool -K {{suricata_sniffing_interface}} rx off
    - ethtool -K {{suricata_sniffing_interface}} tx off
    - ethtool -K {{suricata_sniffing_interface}} sg off
    - ethtool -K {{suricata_sniffing_interface}} rxvlan off
    - ethtool -K {{suricata_sniffing_interface}} txvlan off
  ignore_errors: True
  tags:
    - disable-network-offloading
    - deploy-packages


- name: Check if irqbalance is enabled
  command: sysv-rc-conf  --list irqbalance
  register: chkconfig_status
  tags: disable-network-offloading


- name: DISABLE irqbalance if enabled
  command: chkconfig irqbalance off
  ignore_errors: True
  when: chkconfig_status.stdout.find(":on") != -1
  tags: disable-network-offloading


- name: Deploy suricata.yaml
  template: src=etc/suricata/suricata.yaml.j2 dest=/etc/suricata/suricata.yaml mode=0640 owner=root group=root
  tags: deploy-confs

- name: Deploy Suricata init script
  template: src=etc/init/suricata.conf.j2 dest=/etc/init/suricata.conf mode=0640 owner=root group=root
  tags: deploy-conf


- name: Deploy oinkmaster.conf
  template: src=etc/oinkmaster.conf.j2 dest=/etc/oinkmaster.conf mode=0640 owner=root group=root
  tags: deploy-confs


- name: Updating ruleset
  command: 'oinkmaster -C /etc/oinkmaster.conf -o /etc/suricata/rules'
  tags: update-ruleset
  notify:
    - restart suricata


- name: Deploy scripts
  template: src=opt/{{ item }}.sh.j2 dest=/opt/{{ item }}.sh
            mode=755
            owner=root
            group=root
  with_items:
    - disable_network_offload
    - update_oinkmaster_ruleset
  tags:
    - deploy-cronjobs


- cron: name="Add cronjob at reboot - disbale network offload"
        special_time=reboot
        job="/opt/disable_network_offload.sh"
  tags:
    - deploy-cronjobs


- cron: name="Add cronjob: Daily - Update oinkmaster ruleset"
        special_time=daily
        job=/opt/update_oinkmaster_ruleset.sh
  tags:
    - deploy-cronjobs


